parser: babel-eslint

globals:
  process: true

env:
  browser: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 2018

plugins:
  - react
  - prettier

rules:
  max-len:
    - 2
    - 80
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
  no-console: 0
  react/prop-types: 0

settings:
  react:
    version: '16.6'
